name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 21 ]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Test
        run: ./gradlew --no-daemon clean build jacocoTestReport jacocoTestCoverageVerification

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-jdk-${{ matrix.java }}
          path: build/reports/jacoco/test/html

      - name: Archive JUnit reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports-jdk-${{ matrix.java }}
          path: |
            build/test-results/test
            build/reports/tests/test
