name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 21 ]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build & Test
        run: mvn -B clean verify

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-jdk-${{ matrix.java }}   # 👈 уникальное имя
          path: target/site/jacoco

      - name: Archive surefire reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-jdk-${{ matrix.java }}  # 👈 уникальное имя
          path: |
            **/target/surefire-reports
            **/target/failsafe-reports
